### ISSUE TITLE
대표페이지/header

### ISSUE THREAD

**Issue by oratio100** [ormcamp-fe-3rd/Orm-Tour#3]
- [x] html 레이아웃
- [x] css 적용
- [ ] 휠 JS

**Comment by Devkdy22** [comment]
### header 구현 내용 정리
**header 구성 요소**

1. 로고
2. 메뉴 (메인 페이지 섹션 별 + 예약 확인 페이지 메뉴)

휠 Js 는 메인페이지에 적절한 기능이 아닌 듯하여 제외 (회의 결과)
메뉴 마우스 hover 시 와 클릭 시 underline으로 보여지게 구현
